services:
  postgres:
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    image: postgres:13.3
    environment:
      PG_DATA: /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  notion_db_creator:
    image: postgres:13.3
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: |
      bash -c "
        until pg_isready -h postgres -U postgres; do
          echo 'Waiting for PostgreSQL to be ready...'
          sleep 2
        done
        echo 'PostgreSQL is ready. Creating database...'
        PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U postgres -c 'CREATE DATABASE notion;'
      "

  notion_backend:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - postgres
    volumes:
      - .:/app
      - .:/node_modules
